/*
 * Copyright 2026 Vipshop Inc. All Rights Reserved.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relevance.proto

package com.red.search.relevance.server;

public final class RelevanceProto {
  private RelevanceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RelevanceDispatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:relevance.server.RelevanceDispatch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string feature_version = 1;</code>
     */
    String getFeatureVersion();
    /**
     * <code>optional string feature_version = 1;</code>
     */
    com.google.protobuf.ByteString
        getFeatureVersionBytes();

    /**
     * <code>optional string model_name = 2;</code>
     */
    String getModelName();
    /**
     * <code>optional string model_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getModelNameBytes();

    /**
     * <code>optional string kkv_name = 3;</code>
     */
    String getKkvName();
    /**
     * <code>optional string kkv_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getKkvNameBytes();

    /**
     * <code>optional string ann_name = 4;</code>
     */
    String getAnnName();
    /**
     * <code>optional string ann_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getAnnNameBytes();
  }
  /**
   * Protobuf type {@code relevance.server.RelevanceDispatch}
   */
  public  static final class RelevanceDispatch extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:relevance.server.RelevanceDispatch)
      RelevanceDispatchOrBuilder {
    // Use RelevanceDispatch.newBuilder() to construct.
    private RelevanceDispatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RelevanceDispatch() {
      featureVersion_ = "";
      modelName_ = "";
      kkvName_ = "";
      annName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RelevanceDispatch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              featureVersion_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              modelName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              kkvName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              annName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceDispatch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceDispatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.class, com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder.class);
    }

    public static final int FEATURE_VERSION_FIELD_NUMBER = 1;
    private volatile Object featureVersion_;
    /**
     * <code>optional string feature_version = 1;</code>
     */
    public String getFeatureVersion() {
      Object ref = featureVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        featureVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string feature_version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFeatureVersionBytes() {
      Object ref = featureVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        featureVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_NAME_FIELD_NUMBER = 2;
    private volatile Object modelName_;
    /**
     * <code>optional string model_name = 2;</code>
     */
    public String getModelName() {
      Object ref = modelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string model_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      Object ref = modelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KKV_NAME_FIELD_NUMBER = 3;
    private volatile Object kkvName_;
    /**
     * <code>optional string kkv_name = 3;</code>
     */
    public String getKkvName() {
      Object ref = kkvName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        kkvName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string kkv_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKkvNameBytes() {
      Object ref = kkvName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        kkvName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANN_NAME_FIELD_NUMBER = 4;
    private volatile Object annName_;
    /**
     * <code>optional string ann_name = 4;</code>
     */
    public String getAnnName() {
      Object ref = annName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        annName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ann_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAnnNameBytes() {
      Object ref = annName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        annName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFeatureVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, featureVersion_);
      }
      if (!getModelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, modelName_);
      }
      if (!getKkvNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, kkvName_);
      }
      if (!getAnnNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, annName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFeatureVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, featureVersion_);
      }
      if (!getModelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, modelName_);
      }
      if (!getKkvNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, kkvName_);
      }
      if (!getAnnNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, annName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.red.search.relevance.server.RelevanceProto.RelevanceDispatch)) {
        return super.equals(obj);
      }
      com.red.search.relevance.server.RelevanceProto.RelevanceDispatch other = (com.red.search.relevance.server.RelevanceProto.RelevanceDispatch) obj;

      boolean result = true;
      result = result && getFeatureVersion()
          .equals(other.getFeatureVersion());
      result = result && getModelName()
          .equals(other.getModelName());
      result = result && getKkvName()
          .equals(other.getKkvName());
      result = result && getAnnName()
          .equals(other.getAnnName());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + FEATURE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureVersion().hashCode();
      hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getModelName().hashCode();
      hash = (37 * hash) + KKV_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getKkvName().hashCode();
      hash = (37 * hash) + ANN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAnnName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.red.search.relevance.server.RelevanceProto.RelevanceDispatch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code relevance.server.RelevanceDispatch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:relevance.server.RelevanceDispatch)
        com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceDispatch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceDispatch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.class, com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder.class);
      }

      // Construct using com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        featureVersion_ = "";

        modelName_ = "";

        kkvName_ = "";

        annName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceDispatch_descriptor;
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch getDefaultInstanceForType() {
        return com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.getDefaultInstance();
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch build() {
        com.red.search.relevance.server.RelevanceProto.RelevanceDispatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch buildPartial() {
        com.red.search.relevance.server.RelevanceProto.RelevanceDispatch result = new com.red.search.relevance.server.RelevanceProto.RelevanceDispatch(this);
        result.featureVersion_ = featureVersion_;
        result.modelName_ = modelName_;
        result.kkvName_ = kkvName_;
        result.annName_ = annName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.red.search.relevance.server.RelevanceProto.RelevanceDispatch) {
          return mergeFrom((com.red.search.relevance.server.RelevanceProto.RelevanceDispatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.red.search.relevance.server.RelevanceProto.RelevanceDispatch other) {
        if (other == com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.getDefaultInstance()) return this;
        if (!other.getFeatureVersion().isEmpty()) {
          featureVersion_ = other.featureVersion_;
          onChanged();
        }
        if (!other.getModelName().isEmpty()) {
          modelName_ = other.modelName_;
          onChanged();
        }
        if (!other.getKkvName().isEmpty()) {
          kkvName_ = other.kkvName_;
          onChanged();
        }
        if (!other.getAnnName().isEmpty()) {
          annName_ = other.annName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.red.search.relevance.server.RelevanceProto.RelevanceDispatch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.red.search.relevance.server.RelevanceProto.RelevanceDispatch) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object featureVersion_ = "";
      /**
       * <code>optional string feature_version = 1;</code>
       */
      public String getFeatureVersion() {
        Object ref = featureVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          featureVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string feature_version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFeatureVersionBytes() {
        Object ref = featureVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          featureVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string feature_version = 1;</code>
       */
      public Builder setFeatureVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        featureVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string feature_version = 1;</code>
       */
      public Builder clearFeatureVersion() {
        
        featureVersion_ = getDefaultInstance().getFeatureVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string feature_version = 1;</code>
       */
      public Builder setFeatureVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        featureVersion_ = value;
        onChanged();
        return this;
      }

      private Object modelName_ = "";
      /**
       * <code>optional string model_name = 2;</code>
       */
      public String getModelName() {
        Object ref = modelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          modelName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string model_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getModelNameBytes() {
        Object ref = modelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          modelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string model_name = 2;</code>
       */
      public Builder setModelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string model_name = 2;</code>
       */
      public Builder clearModelName() {
        
        modelName_ = getDefaultInstance().getModelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string model_name = 2;</code>
       */
      public Builder setModelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        modelName_ = value;
        onChanged();
        return this;
      }

      private Object kkvName_ = "";
      /**
       * <code>optional string kkv_name = 3;</code>
       */
      public String getKkvName() {
        Object ref = kkvName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          kkvName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string kkv_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKkvNameBytes() {
        Object ref = kkvName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          kkvName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string kkv_name = 3;</code>
       */
      public Builder setKkvName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kkvName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string kkv_name = 3;</code>
       */
      public Builder clearKkvName() {
        
        kkvName_ = getDefaultInstance().getKkvName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string kkv_name = 3;</code>
       */
      public Builder setKkvNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kkvName_ = value;
        onChanged();
        return this;
      }

      private Object annName_ = "";
      /**
       * <code>optional string ann_name = 4;</code>
       */
      public String getAnnName() {
        Object ref = annName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          annName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ann_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAnnNameBytes() {
        Object ref = annName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          annName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ann_name = 4;</code>
       */
      public Builder setAnnName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        annName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ann_name = 4;</code>
       */
      public Builder clearAnnName() {
        
        annName_ = getDefaultInstance().getAnnName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ann_name = 4;</code>
       */
      public Builder setAnnNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        annName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:relevance.server.RelevanceDispatch)
    }

    // @@protoc_insertion_point(class_scope:relevance.server.RelevanceDispatch)
    private static final com.red.search.relevance.server.RelevanceProto.RelevanceDispatch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.red.search.relevance.server.RelevanceProto.RelevanceDispatch();
    }

    public static com.red.search.relevance.server.RelevanceProto.RelevanceDispatch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RelevanceDispatch>
        PARSER = new com.google.protobuf.AbstractParser<RelevanceDispatch>() {
      public RelevanceDispatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RelevanceDispatch(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RelevanceDispatch> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RelevanceDispatch> getParserForType() {
      return PARSER;
    }

    public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RelevanceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:relevance.server.RelevanceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
     */
    boolean hasDispatch();
    /**
     * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
     */
    com.red.search.relevance.server.RelevanceProto.RelevanceDispatch getDispatch();
    /**
     * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
     */
    com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder getDispatchOrBuilder();

    /**
     * <code>optional string qp_info = 2;</code>
     */
    String getQpInfo();
    /**
     * <code>optional string qp_info = 2;</code>
     */
    com.google.protobuf.ByteString
        getQpInfoBytes();

    /**
     * <code>repeated float query_ann = 3;</code>
     */
    java.util.List<Float> getQueryAnnList();
    /**
     * <code>repeated float query_ann = 3;</code>
     */
    int getQueryAnnCount();
    /**
     * <code>repeated float query_ann = 3;</code>
     */
    float getQueryAnn(int index);

    /**
     * <code>repeated string ids = 4;</code>
     */
    java.util.List<String>
        getIdsList();
    /**
     * <code>repeated string ids = 4;</code>
     */
    int getIdsCount();
    /**
     * <code>repeated string ids = 4;</code>
     */
    String getIds(int index);
    /**
     * <code>repeated string ids = 4;</code>
     */
    com.google.protobuf.ByteString
        getIdsBytes(int index);
  }
  /**
   * Protobuf type {@code relevance.server.RelevanceRequest}
   */
  public  static final class RelevanceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:relevance.server.RelevanceRequest)
      RelevanceRequestOrBuilder {
    // Use RelevanceRequest.newBuilder() to construct.
    private RelevanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RelevanceRequest() {
      qpInfo_ = "";
      queryAnn_ = java.util.Collections.emptyList();
      ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RelevanceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder subBuilder = null;
              if (dispatch_ != null) {
                subBuilder = dispatch_.toBuilder();
              }
              dispatch_ = input.readMessage(com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dispatch_);
                dispatch_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              qpInfo_ = s;
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                queryAnn_ = new java.util.ArrayList<Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              queryAnn_.add(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                queryAnn_ = new java.util.ArrayList<Float>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                queryAnn_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                ids_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              ids_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          queryAnn_ = java.util.Collections.unmodifiableList(queryAnn_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          ids_ = ids_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.red.search.relevance.server.RelevanceProto.RelevanceRequest.class, com.red.search.relevance.server.RelevanceProto.RelevanceRequest.Builder.class);
    }

    private int bitField0_;
    public static final int DISPATCH_FIELD_NUMBER = 1;
    private com.red.search.relevance.server.RelevanceProto.RelevanceDispatch dispatch_;
    /**
     * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
     */
    public boolean hasDispatch() {
      return dispatch_ != null;
    }
    /**
     * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
     */
    public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch getDispatch() {
      return dispatch_ == null ? com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.getDefaultInstance() : dispatch_;
    }
    /**
     * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
     */
    public com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder getDispatchOrBuilder() {
      return getDispatch();
    }

    public static final int QP_INFO_FIELD_NUMBER = 2;
    private volatile Object qpInfo_;
    /**
     * <code>optional string qp_info = 2;</code>
     */
    public String getQpInfo() {
      Object ref = qpInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        qpInfo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string qp_info = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQpInfoBytes() {
      Object ref = qpInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        qpInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERY_ANN_FIELD_NUMBER = 3;
    private java.util.List<Float> queryAnn_;
    /**
     * <code>repeated float query_ann = 3;</code>
     */
    public java.util.List<Float>
        getQueryAnnList() {
      return queryAnn_;
    }
    /**
     * <code>repeated float query_ann = 3;</code>
     */
    public int getQueryAnnCount() {
      return queryAnn_.size();
    }
    /**
     * <code>repeated float query_ann = 3;</code>
     */
    public float getQueryAnn(int index) {
      return queryAnn_.get(index);
    }
    private int queryAnnMemoizedSerializedSize = -1;

    public static final int IDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList ids_;
    /**
     * <code>repeated string ids = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated string ids = 4;</code>
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated string ids = 4;</code>
     */
    public String getIds(int index) {
      return ids_.get(index);
    }
    /**
     * <code>repeated string ids = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIdsBytes(int index) {
      return ids_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (dispatch_ != null) {
        output.writeMessage(1, getDispatch());
      }
      if (!getQpInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, qpInfo_);
      }
      if (getQueryAnnList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(queryAnnMemoizedSerializedSize);
      }
      for (int i = 0; i < queryAnn_.size(); i++) {
        output.writeFloatNoTag(queryAnn_.get(i));
      }
      for (int i = 0; i < ids_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ids_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dispatch_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDispatch());
      }
      if (!getQpInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, qpInfo_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getQueryAnnList().size();
        size += dataSize;
        if (!getQueryAnnList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        queryAnnMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += computeStringSizeNoTag(ids_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.red.search.relevance.server.RelevanceProto.RelevanceRequest)) {
        return super.equals(obj);
      }
      com.red.search.relevance.server.RelevanceProto.RelevanceRequest other = (com.red.search.relevance.server.RelevanceProto.RelevanceRequest) obj;

      boolean result = true;
      result = result && (hasDispatch() == other.hasDispatch());
      if (hasDispatch()) {
        result = result && getDispatch()
            .equals(other.getDispatch());
      }
      result = result && getQpInfo()
          .equals(other.getQpInfo());
      result = result && getQueryAnnList()
          .equals(other.getQueryAnnList());
      result = result && getIdsList()
          .equals(other.getIdsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDispatch()) {
        hash = (37 * hash) + DISPATCH_FIELD_NUMBER;
        hash = (53 * hash) + getDispatch().hashCode();
      }
      hash = (37 * hash) + QP_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getQpInfo().hashCode();
      if (getQueryAnnCount() > 0) {
        hash = (37 * hash) + QUERY_ANN_FIELD_NUMBER;
        hash = (53 * hash) + getQueryAnnList().hashCode();
      }
      if (getIdsCount() > 0) {
        hash = (37 * hash) + IDS_FIELD_NUMBER;
        hash = (53 * hash) + getIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.red.search.relevance.server.RelevanceProto.RelevanceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code relevance.server.RelevanceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:relevance.server.RelevanceRequest)
        com.red.search.relevance.server.RelevanceProto.RelevanceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.red.search.relevance.server.RelevanceProto.RelevanceRequest.class, com.red.search.relevance.server.RelevanceProto.RelevanceRequest.Builder.class);
      }

      // Construct using com.red.search.relevance.server.RelevanceProto.RelevanceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (dispatchBuilder_ == null) {
          dispatch_ = null;
        } else {
          dispatch_ = null;
          dispatchBuilder_ = null;
        }
        qpInfo_ = "";

        queryAnn_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceRequest_descriptor;
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceRequest getDefaultInstanceForType() {
        return com.red.search.relevance.server.RelevanceProto.RelevanceRequest.getDefaultInstance();
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceRequest build() {
        com.red.search.relevance.server.RelevanceProto.RelevanceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceRequest buildPartial() {
        com.red.search.relevance.server.RelevanceProto.RelevanceRequest result = new com.red.search.relevance.server.RelevanceProto.RelevanceRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (dispatchBuilder_ == null) {
          result.dispatch_ = dispatch_;
        } else {
          result.dispatch_ = dispatchBuilder_.build();
        }
        result.qpInfo_ = qpInfo_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          queryAnn_ = java.util.Collections.unmodifiableList(queryAnn_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.queryAnn_ = queryAnn_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          ids_ = ids_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.ids_ = ids_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.red.search.relevance.server.RelevanceProto.RelevanceRequest) {
          return mergeFrom((com.red.search.relevance.server.RelevanceProto.RelevanceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.red.search.relevance.server.RelevanceProto.RelevanceRequest other) {
        if (other == com.red.search.relevance.server.RelevanceProto.RelevanceRequest.getDefaultInstance()) return this;
        if (other.hasDispatch()) {
          mergeDispatch(other.getDispatch());
        }
        if (!other.getQpInfo().isEmpty()) {
          qpInfo_ = other.qpInfo_;
          onChanged();
        }
        if (!other.queryAnn_.isEmpty()) {
          if (queryAnn_.isEmpty()) {
            queryAnn_ = other.queryAnn_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureQueryAnnIsMutable();
            queryAnn_.addAll(other.queryAnn_);
          }
          onChanged();
        }
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.red.search.relevance.server.RelevanceProto.RelevanceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.red.search.relevance.server.RelevanceProto.RelevanceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.red.search.relevance.server.RelevanceProto.RelevanceDispatch dispatch_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.red.search.relevance.server.RelevanceProto.RelevanceDispatch, com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder, com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder> dispatchBuilder_;
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public boolean hasDispatch() {
        return dispatchBuilder_ != null || dispatch_ != null;
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch getDispatch() {
        if (dispatchBuilder_ == null) {
          return dispatch_ == null ? com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.getDefaultInstance() : dispatch_;
        } else {
          return dispatchBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public Builder setDispatch(com.red.search.relevance.server.RelevanceProto.RelevanceDispatch value) {
        if (dispatchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dispatch_ = value;
          onChanged();
        } else {
          dispatchBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public Builder setDispatch(
          com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder builderForValue) {
        if (dispatchBuilder_ == null) {
          dispatch_ = builderForValue.build();
          onChanged();
        } else {
          dispatchBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public Builder mergeDispatch(com.red.search.relevance.server.RelevanceProto.RelevanceDispatch value) {
        if (dispatchBuilder_ == null) {
          if (dispatch_ != null) {
            dispatch_ =
              com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.newBuilder(dispatch_).mergeFrom(value).buildPartial();
          } else {
            dispatch_ = value;
          }
          onChanged();
        } else {
          dispatchBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public Builder clearDispatch() {
        if (dispatchBuilder_ == null) {
          dispatch_ = null;
          onChanged();
        } else {
          dispatch_ = null;
          dispatchBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder getDispatchBuilder() {
        
        onChanged();
        return getDispatchFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      public com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder getDispatchOrBuilder() {
        if (dispatchBuilder_ != null) {
          return dispatchBuilder_.getMessageOrBuilder();
        } else {
          return dispatch_ == null ?
              com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.getDefaultInstance() : dispatch_;
        }
      }
      /**
       * <code>optional .relevance.server.RelevanceDispatch dispatch = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.red.search.relevance.server.RelevanceProto.RelevanceDispatch, com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder, com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder> 
          getDispatchFieldBuilder() {
        if (dispatchBuilder_ == null) {
          dispatchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.red.search.relevance.server.RelevanceProto.RelevanceDispatch, com.red.search.relevance.server.RelevanceProto.RelevanceDispatch.Builder, com.red.search.relevance.server.RelevanceProto.RelevanceDispatchOrBuilder>(
                  getDispatch(),
                  getParentForChildren(),
                  isClean());
          dispatch_ = null;
        }
        return dispatchBuilder_;
      }

      private Object qpInfo_ = "";
      /**
       * <code>optional string qp_info = 2;</code>
       */
      public String getQpInfo() {
        Object ref = qpInfo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          qpInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string qp_info = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQpInfoBytes() {
        Object ref = qpInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          qpInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string qp_info = 2;</code>
       */
      public Builder setQpInfo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        qpInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string qp_info = 2;</code>
       */
      public Builder clearQpInfo() {
        
        qpInfo_ = getDefaultInstance().getQpInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string qp_info = 2;</code>
       */
      public Builder setQpInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        qpInfo_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Float> queryAnn_ = java.util.Collections.emptyList();
      private void ensureQueryAnnIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          queryAnn_ = new java.util.ArrayList<Float>(queryAnn_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public java.util.List<Float>
          getQueryAnnList() {
        return java.util.Collections.unmodifiableList(queryAnn_);
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public int getQueryAnnCount() {
        return queryAnn_.size();
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public float getQueryAnn(int index) {
        return queryAnn_.get(index);
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public Builder setQueryAnn(
          int index, float value) {
        ensureQueryAnnIsMutable();
        queryAnn_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public Builder addQueryAnn(float value) {
        ensureQueryAnnIsMutable();
        queryAnn_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public Builder addAllQueryAnn(
          Iterable<? extends Float> values) {
        ensureQueryAnnIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queryAnn_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float query_ann = 3;</code>
       */
      public Builder clearQueryAnn() {
        queryAnn_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          ids_ = new com.google.protobuf.LazyStringArrayList(ids_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIdsList() {
        return ids_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public String getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIdsBytes(int index) {
        return ids_.getByteString(index);
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public Builder setIds(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public Builder addIds(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public Builder addAllIds(
          Iterable<String> values) {
        ensureIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public Builder clearIds() {
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 4;</code>
       */
      public Builder addIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:relevance.server.RelevanceRequest)
    }

    // @@protoc_insertion_point(class_scope:relevance.server.RelevanceRequest)
    private static final com.red.search.relevance.server.RelevanceProto.RelevanceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.red.search.relevance.server.RelevanceProto.RelevanceRequest();
    }

    public static com.red.search.relevance.server.RelevanceProto.RelevanceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RelevanceRequest>
        PARSER = new com.google.protobuf.AbstractParser<RelevanceRequest>() {
      public RelevanceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RelevanceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RelevanceRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RelevanceRequest> getParserForType() {
      return PARSER;
    }

    public com.red.search.relevance.server.RelevanceProto.RelevanceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RelevanceReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:relevance.server.RelevanceReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float scores = 1;</code>
     */
    java.util.List<Float> getScoresList();
    /**
     * <code>repeated float scores = 1;</code>
     */
    int getScoresCount();
    /**
     * <code>repeated float scores = 1;</code>
     */
    float getScores(int index);
  }
  /**
   * Protobuf type {@code relevance.server.RelevanceReply}
   */
  public  static final class RelevanceReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:relevance.server.RelevanceReply)
      RelevanceReplyOrBuilder {
    // Use RelevanceReply.newBuilder() to construct.
    private RelevanceReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RelevanceReply() {
      scores_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RelevanceReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                scores_ = new java.util.ArrayList<Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              scores_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                scores_ = new java.util.ArrayList<Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                scores_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.red.search.relevance.server.RelevanceProto.RelevanceReply.class, com.red.search.relevance.server.RelevanceProto.RelevanceReply.Builder.class);
    }

    public static final int SCORES_FIELD_NUMBER = 1;
    private java.util.List<Float> scores_;
    /**
     * <code>repeated float scores = 1;</code>
     */
    public java.util.List<Float>
        getScoresList() {
      return scores_;
    }
    /**
     * <code>repeated float scores = 1;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <code>repeated float scores = 1;</code>
     */
    public float getScores(int index) {
      return scores_.get(index);
    }
    private int scoresMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getScoresList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(scoresMemoizedSerializedSize);
      }
      for (int i = 0; i < scores_.size(); i++) {
        output.writeFloatNoTag(scores_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getScoresList().size();
        size += dataSize;
        if (!getScoresList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        scoresMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.red.search.relevance.server.RelevanceProto.RelevanceReply)) {
        return super.equals(obj);
      }
      com.red.search.relevance.server.RelevanceProto.RelevanceReply other = (com.red.search.relevance.server.RelevanceProto.RelevanceReply) obj;

      boolean result = true;
      result = result && getScoresList()
          .equals(other.getScoresList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getScoresCount() > 0) {
        hash = (37 * hash) + SCORES_FIELD_NUMBER;
        hash = (53 * hash) + getScoresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.red.search.relevance.server.RelevanceProto.RelevanceReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code relevance.server.RelevanceReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:relevance.server.RelevanceReply)
        com.red.search.relevance.server.RelevanceProto.RelevanceReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.red.search.relevance.server.RelevanceProto.RelevanceReply.class, com.red.search.relevance.server.RelevanceProto.RelevanceReply.Builder.class);
      }

      // Construct using com.red.search.relevance.server.RelevanceProto.RelevanceReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.red.search.relevance.server.RelevanceProto.internal_static_relevance_server_RelevanceReply_descriptor;
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceReply getDefaultInstanceForType() {
        return com.red.search.relevance.server.RelevanceProto.RelevanceReply.getDefaultInstance();
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceReply build() {
        com.red.search.relevance.server.RelevanceProto.RelevanceReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.red.search.relevance.server.RelevanceProto.RelevanceReply buildPartial() {
        com.red.search.relevance.server.RelevanceProto.RelevanceReply result = new com.red.search.relevance.server.RelevanceProto.RelevanceReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scores_ = scores_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.red.search.relevance.server.RelevanceProto.RelevanceReply) {
          return mergeFrom((com.red.search.relevance.server.RelevanceProto.RelevanceReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.red.search.relevance.server.RelevanceProto.RelevanceReply other) {
        if (other == com.red.search.relevance.server.RelevanceProto.RelevanceReply.getDefaultInstance()) return this;
        if (!other.scores_.isEmpty()) {
          if (scores_.isEmpty()) {
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScoresIsMutable();
            scores_.addAll(other.scores_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.red.search.relevance.server.RelevanceProto.RelevanceReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.red.search.relevance.server.RelevanceProto.RelevanceReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Float> scores_ = java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = new java.util.ArrayList<Float>(scores_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public java.util.List<Float>
          getScoresList() {
        return java.util.Collections.unmodifiableList(scores_);
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public int getScoresCount() {
        return scores_.size();
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public float getScores(int index) {
        return scores_.get(index);
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public Builder setScores(
          int index, float value) {
        ensureScoresIsMutable();
        scores_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public Builder addScores(float value) {
        ensureScoresIsMutable();
        scores_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public Builder addAllScores(
          Iterable<? extends Float> values) {
        ensureScoresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scores_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float scores = 1;</code>
       */
      public Builder clearScores() {
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:relevance.server.RelevanceReply)
    }

    // @@protoc_insertion_point(class_scope:relevance.server.RelevanceReply)
    private static final com.red.search.relevance.server.RelevanceProto.RelevanceReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.red.search.relevance.server.RelevanceProto.RelevanceReply();
    }

    public static com.red.search.relevance.server.RelevanceProto.RelevanceReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RelevanceReply>
        PARSER = new com.google.protobuf.AbstractParser<RelevanceReply>() {
      public RelevanceReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RelevanceReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RelevanceReply> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RelevanceReply> getParserForType() {
      return PARSER;
    }

    public com.red.search.relevance.server.RelevanceProto.RelevanceReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_relevance_server_RelevanceDispatch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_relevance_server_RelevanceDispatch_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_relevance_server_RelevanceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_relevance_server_RelevanceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_relevance_server_RelevanceReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_relevance_server_RelevanceReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017relevance.proto\022\020relevance.server\"d\n\021R" +
      "elevanceDispatch\022\027\n\017feature_version\030\001 \001(" +
      "\t\022\022\n\nmodel_name\030\002 \001(\t\022\020\n\010kkv_name\030\003 \001(\t\022" +
      "\020\n\010ann_name\030\004 \001(\t\"z\n\020RelevanceRequest\0225\n" +
      "\010dispatch\030\001 \001(\0132#.relevance.server.Relev" +
      "anceDispatch\022\017\n\007qp_info\030\002 \001(\t\022\021\n\tquery_a" +
      "nn\030\003 \003(\002\022\013\n\003ids\030\004 \003(\t\" \n\016RelevanceReply\022" +
      "\016\n\006scores\030\001 \003(\0022^\n\tRelevance\022Q\n\007Predict\022" +
      "\".relevance.server.RelevanceRequest\032 .re" +
      "levance.server.RelevanceReply\"\000B\023B\016Relev",
      "anceProto\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_relevance_server_RelevanceDispatch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_relevance_server_RelevanceDispatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_relevance_server_RelevanceDispatch_descriptor,
        new String[] { "FeatureVersion", "ModelName", "KkvName", "AnnName", });
    internal_static_relevance_server_RelevanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_relevance_server_RelevanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_relevance_server_RelevanceRequest_descriptor,
        new String[] { "Dispatch", "QpInfo", "QueryAnn", "Ids", });
    internal_static_relevance_server_RelevanceReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_relevance_server_RelevanceReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_relevance_server_RelevanceReply_descriptor,
        new String[] { "Scores", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
